##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.3.0-B58] date: [Wed Feb 26 09:54:01 CST 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = EVSPIN32G4_Shinano


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -O0


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/app_freertos.c \
Src/motorcontrol.c \
Src/pwm_common.c \
Src/mc_api.c \
Src/mc_config.c \
Src/mc_config_common.c \
Src/mcp_config.c \
Src/mc_tasks.c \
Src/mc_tasks_foc.c \
Src/pwm_curr_fdbk.c \
Src/regular_conversion_manager.c \
Src/mc_math.c \
Src/mc_interface.c \
Src/stm32_mc_common_it.c \
Src/stm32g4xx_mc_it.c \
Src/mc_parameters.c \
Src/register_interface.c \
Src/mcp.c \
Src/mc_perf.c \
Src/usart_aspep_driver.c \
Src/mc_configuration_registers.c \
Src/aspep.c \
Src/mc_app_hooks.c \
Src/stm32g4xx_it.c \
Src/stm32g4xx_hal_msp.c \
Src/stm32g4xx_hal_timebase_tim.c \
Src/vesc_uart.c \
Src/tim.c \
Src/nvm.c \
Src/spi.c \
Src/dma.c \
Src/arm_cos_f32.c \
Src/arm_sin_f32.c \
Src/interface_uart.c \
Src/freertos_var.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_utils.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_adc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_comp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_cordic.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_dac.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_i2c.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_opamp.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_tim_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_tim.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_ll_usart.c \
Src/system_stm32g4xx.c \
Middlewares/Third_Party/FreeRTOS/Source/croutine.c \
Middlewares/Third_Party/FreeRTOS/Source/event_groups.c \
Middlewares/Third_Party/FreeRTOS/Source/list.c \
Middlewares/Third_Party/FreeRTOS/Source/queue.c \
Middlewares/Third_Party/FreeRTOS/Source/stream_buffer.c \
Middlewares/Third_Party/FreeRTOS/Source/tasks.c \
Middlewares/Third_Party/FreeRTOS/Source/timers.c \
Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS/cmsis_os.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/MemMang/heap_4.c \
Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/G4xx/Src/stspin32g4.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/bus_voltage_sensor.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/circle_limitation.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/digital_output.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/feed_forward_ctrl.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pwm_curr_fdbk_ovm.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ntc_temperature_sensor.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/open_loop.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pid_regulator.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/pqd_motor_power_measurement.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/r_divider_bus_voltage_sensor.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/ramp_ext_mngr.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/revup_ctrl.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_pos_fdbk.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/speed_torq_ctrl.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/sto_pll_speed_pos_fdbk.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/virtual_speed_sensor.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/G4xx/Src/r3_2_g4xx_pwm_curr_fdbk.c \
MCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Src/mcpa.c \
Src/sysmem.c \
Src/syscalls.c \
Src/div.c 


# Add after C_SOURCES definition
# C++ sources
CPP_SOURCES = \
Src/config_system.cpp \
Src/motor.cpp \
Src/foc.cpp \
Src/utils.cpp \
Src/low_level.cpp \
Src/interface_can.cpp \
Src/main_.cpp \
Src/can_encos.cpp \
Src/axis.cpp \
Src/controller.cpp \
Src/encoder.cpp \
Src/thermistor.cpp \
Src/open_loop_controller.cpp \
Src/canopen.cpp \





# Add to binaries section after CC definition
CXX = $(PREFIX)g++

# Add after CFLAGS definition
# C++ flags
CXXFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections
CXXFLAGS += -std=c++17 -Wno-register  # Add C++17 support
CXXFLAGS += -fno-exceptions -fno-rtti
CXXFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"
CXXFLAGS += -D_GLIBCXX_USE_CXX11_ABI=1
CXXFLAGS += -fno-sized-deallocation
CXXFLAGS += -fshort-wchar
CFLAGS += -fshort-wchar
ifeq ($(DEBUG), 1)
CXXFLAGS += -g -gdwarf-2
endif
# ASM sources
ASM_SOURCES =  \
startup_stm32g431xx.s

# ASM sources
ASMM_SOURCES = 


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DARM_MATH_CM4 \
-DUSE_FULL_LL_DRIVER \
-DUSE_HAL_DRIVER \
-DSTM32G431xx


# AS includes
AS_INCLUDES =  \
-IInc

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32G4xx_HAL_Driver/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/Third_Party/FreeRTOS/Source/include \
-IMiddlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS \
-IMiddlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F \
-IMCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/G4xx/Inc \
-IMCSDK_v6.3.2-Full/MotorControl/MCSDK/MCLib/Any/Inc \
-IDrivers/CMSIS/Device/ST/STM32G4xx/Include \
-IDrivers/CMSIS/Include \
-IDrivers/CMSIS/DSP/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G431VBTx_FLASH.ld
LIBDIR += -LMCSDK_v6.3.2-Full/MotorControl/libMP
LIBDIR += -LDrivers/CMSIS/DSP/Lib/GCC
# libraries

LIBS = -lc -lm -lnosys -larm_cortexM4lf_math
LIBS += -lmp-G4-MDK-ARM_ARMv7-M


LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# Add to CXXFLAGS and CFLAGS
CXXFLAGS += -fshort-wchar
CFLAGS += -fshort-wchar



# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


FIRMWARE = $(BUILD_DIR)/$(TARGET).elf


USE_STLINK ?= 0

# Configure OpenOCD for different debuggers
ifeq ($(USE_STLINK),1)
OPENOCD := openocd -f interface/stlink-v2.cfg \
	$(if $(value PROGRAMMER),-c 'hla_serial $(PROGRAMMER)',) \
	-f target/stm32g4x.cfg
else
OPENOCD := openocd -f interface/jlink.cfg \
	$(if $(value PROGRAMMER),-c 'hla_serial $(PROGRAMMER)',) \
	-f target/stm32g4x.cfg
endif



flash: all
	$(OPENOCD) -c init \
		-c 'reset halt' \
		-c 'flash write_image erase $(FIRMWARE)' \
		-c 'reset run' \
		-c exit

asm_build = asm_build

asm: all | $(asm_build) 
	@echo "Generating assembly files..."
	@mkdir -p $(asm_build)  # 确保输出目录存在
	@for src in $(C_SOURCES); do \
		$(CC) -S $(CFLAGS) $$src -o $(asm_build)/$$(basename $$src .c).s; \
	done

asm1: all | $(asm_build)
	@echo "Generating assembly files in $(asm_build) directory..."
	@for src in $(C_SOURCES); do \
        filename=$$(basename $$src .c); \
        $(CC) -S $(CFLAGS) $$src -o $(asm_build)/$$filename.s; \
    done
	@for src in $(CPP_SOURCES); do \
		filename=$$(basename $$src .cpp); \
		$(CXX) -S $(CXXFLAGS) $$src -o $(asm_build)/$$filename.s; \
	done
	@echo "Assembly generation complete!"

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

# Update OBJECTS to include C++ files
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(CPP_SOURCES:.cpp=.o)))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

# Add C++ build rule after C build rule
$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR)
	$(CXX) -c $(CXXFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.cpp=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CXX) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@

$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@

$(BUILD_DIR):
	mkdir $@

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
